## 📁 DF1: `customer_satisfaction`

**→ 고객센터에 문의한 고객의 만족도 기록**

| 컬럼명 | 쉽게 말하면 | 예시 값 | 설명 |
|--------|-------------|---------|------|
| `customer_id` | 고객 번호 | 495 | 개별 고객을 식별하는 ID 번호 |
| `contact_date` | 문의 날짜 | 2023-06-16 | 고객이 고객센터에 연락한 날짜 |
| `contact_reason` | 문의 이유 | technical, shipping 등 | 어떤 이유로 연락했는지 (기술 문제, 배송 문제, 상품 관련 등) |
| `satisfaction_score` | 만족도 점수 (1~5점 예상) | 4.0 | 고객이 문제 해결 후 평가한 만족도 (5점이 가장 만족) |
| `resolution_time_hours` | 문제 해결까지 걸린 시간 (단위: 시간) | 11.4 | 고객센터가 문제를 처리하는 데 걸린 시간 |
| `repeat_contact` | 재문의 여부 | True / False | 같은 문제로 이전에도 연락한 적이 있는지 여부 (True면 재문의한 경우) |

---

## 📁 DF2: `customer_transactions`

**→ 고객의 실제 쇼핑 기록**

| 컬럼명 | 쉽게 말하면 | 예시 값 | 설명 |
|--------|-------------|---------|------|
| `customer_id` | 고객 번호 | 1 | 위 DF1의 고객 ID와 동일하게 사용됨 |
| `registration_date` | 회원가입일 | 2023-04-13 | 고객이 처음으로 회원가입한 날짜 |
| `acquisition_channel` | 유입 경로 | email, social 등 | 어떤 경로(광고, 이메일 등)로 유입되었는지 |
| `customer_segment` | 고객 등급 | premium, basic 등 | 고객을 분류한 그룹 (VIP인지, 일반인지 등) |
| `transaction_date` | 구매 날짜 | 2023-08-22 | 실제로 물건을 구매한 날짜 |
| `order_value` | 구매 금액 | 104.24 | 해당 주문 건에서 결제한 총 금액 |
| `product_category` | 상품 카테고리 | Books, Electronics 등 | 어떤 종류의 제품을 샀는지 |

---

## 📁 DF3: `marketing_performance`

**→ 월별 마케팅 성과 요약**

| 컬럼명 | 쉽게 말하면 | 예시 값 | 설명 |
|--------|-------------|---------|------|
| `month` | 해당 월 | 2023-01-01 | 이 데이터가 어떤 달의 기록인지 |
| `channel` | 마케팅 채널 | organic, paid_search 등 | 어떤 방식의 마케팅인지 (검색, SNS, 이메일, 추천 등) |
| `marketing_spend` | 마케팅 비용 | 11,986.88 | 해당 달에 그 채널에 쓴 광고비 |
| `new_customers` | 신규 고객 수 | 19 | 이 마케팅을 통해 유입된 신규 고객 수 |
| `website_visits` | 사이트 방문 수 | 995 | 마케팅으로 인해 홈페이지에 방문한 횟수 |
| `conversions` | 전환 수 (주문 등) | 19 | 방문자 중 실제 구매/가입 등의 행동을 한 사람 수 |

문제 1: 채널별 고객 획득 비용(CAC) 및 생애 가치(LTV) 분석
목표: 마케팅 채널의 진정한 ROI를 평가하기 위해 CAC와 LTV를 계산하고 최적 투자 전략을 제안하세요.
1. 데이터 로드 및 전처리
2. 채널별 CAC 계산
    - 2024년 데이터만 사용 - (2024년 마케팅데이터만 사용 -> 24년 채녈별 마케팅비용/24년 신규 획득 고객 수)
    - 각 채널별 총 마케팅 비용 집계
    - 각 채널별 신규 고객 수 집계 (2024년 첫 거래 기준)
    - CAC = 총 마케팅 비용 / 신규 고객 수
    - organic과 referral 채널은 CAC = 0으로 처리
3. 고객별 LTV 계산 - 전체 구매 이력 기반
4. 채널별 LTV 및 ROI 분석 - (`24년 신규 고객들의 평균 LTV / 24년 CAC`)    
    - 채널별 평균 LTV 계산
    - ROI = LTV / CAC 계산 (organic, referral은 무한대 처리)
    - payback period = CAC / (월평균 구매금액) 계산
5. 시각화 및 전략 제안 (15분)
    - CAC vs LTV 산점도 차트
    - 채널별 ROI 막대 차트
    - 마케팅 예산 재배분 제안 (현재 vs 최적 배분)

문제 2: 고객 코호트 분석 및 유지율 개선 전략
목표: "월별 가입 코호트"의 유지율과 매출 기여도를 분석하여 고객 유지 전략을 수립하세요.
1. 코호트 그룹 생성
2. 월별 유지율 계산
    - 각 거래의 코호트 대비 경과 개월 수 계산
    - 코호트별 Month 0, 1, 2, ... 12에서의 활성 고객 수
    - 유지율 테이블 생성 (코호트 × 경과월)
    - 평균 유지율 곡선 계산
3. 코호트별 매출 기여도 분석
    - 각 코호트의 월별 누적 매출 계산
    - 코호트별 고객 1인당 누적 매출 (ARPU) 계산
    - 6개월 후, 12개월 후 예상 LTV 추정
4. 유지율 히트맵 시각화
5. 개선 전략 수립
    - 유지율이 급격히 감소하는 시점 식별
    - 고성과 코호트 vs 저성과 코호트 특성 비교
    - 유지율 개선을 위한 액션 아이템 3가지 제안

In [3]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
import warnings

warnings.filterwarnings('ignore', category=UserWarning)
plt.rcParams['font.family'] = 'Malgun Gothic'
plt.rcParams['axes.unicode_minus'] = False

In [4]:
customer_satisfaction = pd.read_csv('./customer_satisfaction.csv')
customer_transactions = pd.read_csv('./customer_transactions.csv')
marketing_performance = pd.read_csv('./marketing_performance.csv')

In [5]:
customer_satisfaction['contact_date'] = pd.to_datetime(customer_satisfaction['contact_date'])
customer_transactions['registration_date'] = pd.to_datetime(customer_transactions['registration_date'])
customer_transactions['transaction_date'] = pd.to_datetime(customer_transactions['transaction_date'])
marketing_performance['month'] = pd.to_datetime(marketing_performance['month'])

2. 채널별 CAC 계산
    - 2024년 데이터만 사용 - (2024년 마케팅데이터만 사용 -> 24년 채녈별 마케팅비용/24년 신규 획득 고객 수)
    - 각 채널별 총 마케팅 비용 집계
    - 각 채널별 신규 고객 수 집계 (2024년 첫 거래 기준)
    - CAC = 총 마케팅 비용 / 신규 고객 수
    - organic과 referral 채널은 CAC = 0으로 처리

In [14]:
cac_per_channel = marketing_performance[marketing_performance['month'].dt.year == 2024].groupby('channel').agg({
    'marketing_spend': 'sum',
    'new_customers': 'sum'
}).rename(columns={
    'marketing_spend': 'marketing_spend_sum',
    'new_customers': 'new_customers_sum'
}).reset_index()

cac_per_channel['cac_2024'] = cac_per_channel.apply(
    lambda row: 0 if row['channel'] in ['organic', 'referral']
    or row['new_customers_sum'] == 0
    else round(row['marketing_spend_sum'] / row['new_customers_sum'], 2),
    axis=1
)

cac_per_channel = cac_per_channel.sort_values('cac_2024', ascending=False).reset_index(drop=True)
cac_per_channel

        channel  marketing_spend_sum  new_customers_sum  cac_2024
0   paid_search         97849.029394                224    436.83
1  social_media         59628.676756                182    327.63
2         email         17763.268813                158    112.43
3       organic             0.000000                302      0.00
4      referral         11867.432377                106      0.00

3. 고객별 LTV 계산 - 전체 구매 이력 기반

In [ ]:
cust_ltv = customer_transactions.groupby('customer_id').agg({
    'order_value': 'sum',
    'transaction_date': ['count', 'max'],
    'registration_date': 'first'
})

cust_ltv.columns = ['_'.join(col) for col in cust_ltv.columns]
cust_ltv = cust_ltv.rename(columns={
    'order_value_sum': 'total_revenue',
    'transaction_date_count': 'transaction_count',
    'registration_date_first': 'registration_date'
}).reset_index()

cust_ltv['cust_lifespan_d'] = (cust_ltv['transaction_date_max'] - cust_ltv['registration_date']).dt.days + 1

# 예외값 제거(Boolean Masking)
cust_ltv = cust_ltv[(cust_ltv['cust_lifespan_d'] > 0) & (cust_ltv['transaction_count'] > 0)]

cust_ltv['total_ltv'] = cust_ltv['total_revenue']
cust_ltv['ltv_per_trans'] = (cust_ltv['total_revenue'] / cust_ltv['transaction_count']).round(2)
cust_ltv['ltv_per_days'] = (cust_ltv['total_revenue'] / cust_ltv['cust_lifespan_d']).round(2)
cust_ltv

,customer_id,total revenue,transaction_count,transaction_date_max,registration_date,cust_lifespan_d,total_ltv,ltv_per_trans,ltv_per_days
0,1,924.73,8,2024-09-23,2023-04-13,530,924.73,115.591250,1.744774
1,2,122.59,2,2023-09-09,2023-05-11,122,122.59,61.295000,1.004836
2,3,72.52,2,2024-06-21,2024-03-30,84,72.52,36.260000,0.863333
3,4,345.55,5,2024-12-14,2024-04-21,238,345.55,69.110000,1.451891
4,5,689.06,5,2024-12-22,2024-04-16,251,689.06,137.812000,2.745259
...,...,...,...,...,...,...,...,...,...
973,996,329.70,4,2024-10-16,2023-11-10,342,329.70,82.425000,0.964035
974,997,1027.43,9,2024-09-16,2023-04-20,516,1027.43,114.158889,1.991143
975,998,190.67,2,2024-12-08,2024-06-07,185,190.67,95.335000,1.030649
976,999,25.21,1,2024-07-30,2024-07-06,25,25.21,25.210000,1.008400
977,1000,115.52,2,2024-12-30,2024-05-04,241,115.52,57.760000,0.479336

4. 채널별 LTV 및 ROI 분석 - (`24년 신규 고객들의 평균 LTV / 24년 CAC`)    
    - 채널별 평균 LTV 계산
    - ROI = LTV / CAC 계산 (organic, referral은 무한대 처리)
    - payback period = CAC / (월평균 구매금액) 계산

In [73]:
revenue_per_channel = customer_transactions.groupby([customer_transactions['transaction_date'].dt.to_period('M').dt.to_timestamp(), 'acquisition_channel']).agg({
    'customer_id': 'count',
    'order_value': 'sum'
}).rename(columns={
    'customer_id': 'order_count'
}).reset_index()

channel_summary = pd.merge(marketing_performance, revenue_per_channel, how='left', left_on=['month', 'channel'], right_on=['transaction_date', 'acquisition_channel'])
channel_summary = channel_summary.drop(['transaction_date', 'acquisition_channel'], axis=1)
channel_summary

,month,channel,marketing_spend,new_customers,website_visits,conversions,order_count,order_value
0,2023-01-01,organic,0.000000,28,511,28,7.0,477.54
1,2023-01-01,paid_search,11986.882840,19,995,19,5.0,445.55
2,2023-01-01,social_media,4235.453095,17,1048,17,4.0,335.78
3,2023-01-01,email,1693.773605,17,1037,17,NaN,NaN
4,2023-01-01,referral,887.489645,10,958,10,NaN,NaN
...,...,...,...,...,...,...,...,...
115,2024-12-01,organic,0.000000,27,505,27,51.0,4928.69
116,2024-12-01,paid_search,6149.273297,20,999,20,44.0,3555.59
117,2024-12-01,social_media,4668.252208,14,1028,14,26.0,2488.23
118,2024-12-01,email,1496.013316,9,1013,9,39.0,3086.51
119,2024-12-01,referral,556.666897,7,986,7,16.0,1696.64

5. 시각화 및 전략 제안 (15분)
    - CAC vs LTV 산점도 차트
    - 채널별 ROI 막대 차트
    - 마케팅 예산 재배분 제안 (현재 vs 최적 배분)